/**
 * VS Code prompt files, generated from the skills.
 *
 * Copilot chat reads `<user data>/prompts/<name>.prompt.md` and exposes each one as
 * `/<name>`. That is a different file format from an agent skill, but it must not
 * become a second copy of the instructions: two hand-maintained copies of the same
 * procedure drift, and the one nobody is looking at is the one that goes stale.
 *
 * So the prompt file is derived from SKILL.md at install time. The skill stays the
 * single source of truth, and `compact` regenerates the description in both.
 */

export const GENERATED_MARKER =
  '<!-- generated by agent-memory from SKILL.md; edits here are overwritten -->';

/** Split a leading `---` frontmatter block from the body. */
function splitFrontmatter(text) {
  const src = String(text).replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');
  if (!src.startsWith('---')) return { head: '', body: src.trim() };
  const end = src.indexOf('\n---', 3);
  if (end === -1) return { head: '', body: src.trim() };
  return {
    head: src.slice(3, end),
    body: src.slice(end + 4).replace(/^\n+/, '').trimEnd(),
  };
}

/**
 * Read one scalar out of a frontmatter block.
 * Handles the quoted form, since a regenerated description contains colons.
 */
function field(head, key) {
  const m = new RegExp(`^${key}:\\s*(.*)$`, 'm').exec(head);
  if (!m) return null;
  const raw = m[1].trim();
  if (raw.startsWith('"')) {
    try {
      return JSON.parse(raw);
    } catch {
      return raw.slice(1, -1);
    }
  }
  return raw;
}

/**
 * Convert a SKILL.md into a VS Code prompt file.
 *
 * `mode: agent` because every one of these skills runs terminal commands; in ask
 * mode they would render as text the model cannot act on.
 */
export function toPromptFile(skillMarkdown, { name } = {}) {
  const { head, body } = splitFrontmatter(skillMarkdown);
  const description = field(head, 'description') || `agent-memory: ${name}`;

  return [
    '---',
    'mode: agent',
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    GENERATED_MARKER,
    '',
    body,
    '',
  ].join('\n');
}

/**
 * Whether a file on disk was written by us.
 *
 * Uninstall removes prompt files by this marker rather than by filename. Somebody
 * may have written their own `recall.prompt.md`, and deleting it because the name
 * matched would be destroying work we were never asked to manage.
 */
export function isGenerated(content) {
  return String(content).includes(GENERATED_MARKER);
}
