/**
 * Fail-closed redaction.
 *
 * The store is plaintext on a corporate desktop and its contents are generated by
 * a model from conversations that may contain secrets. Nothing reaches disk
 * unscanned. A scan that throws aborts the write rather than letting unscanned
 * bytes through, which is what "fail-closed" means here.
 */

const PATTERNS = [
  // Provider-specific credentials first; these are unambiguous.
  { kind: 'aws-access-key', re: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/g },
  { kind: 'github-token', re: /\bgh[pousr]_[A-Za-z0-9]{36,}\b/g },
  { kind: 'slack-token', re: /\bxox[abprs]-[A-Za-z0-9-]{10,}\b/g },
  { kind: 'google-api-key', re: /\bAIza[0-9A-Za-z_-]{35}\b/g },
  { kind: 'anthropic-key', re: /\bsk-ant-[A-Za-z0-9_-]{20,}\b/g },
  { kind: 'openai-key', re: /\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/g },
  {
    kind: 'private-key',
    re: /-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----/g,
  },
  { kind: 'jwt', re: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g },
  { kind: 'bearer-token', re: /\bBearer\s+[A-Za-z0-9._~+/-]{20,}={0,2}/gi },
  // Connection strings carry the credential inline, so the whole URI goes.
  { kind: 'connection-string', re: /\b[a-z][a-z0-9+.-]*:\/\/[^\s:@/]+:[^\s@/]+@[^\s/]+/gi },
  // Assignment-shaped secrets. Requires quotes or a long unquoted run so that
  // ordinary prose like "the password rotation policy" survives untouched.
  {
    kind: 'assigned-secret',
    re: /\b(?:api[_-]?key|secret|password|passwd|pwd|token|client[_-]?secret|access[_-]?key)\b\s*[:=]\s*(?:"[^"\n]{6,}"|'[^'\n]{6,}'|[^\s"'`,;)]{12,})/gi,
  },
  {
    kind: 'session-cookie',
    re: /\b(?:session|sid|auth|jsessionid|phpsessid)[_-]?(?:id|token)?\s*=\s*[A-Za-z0-9._-]{16,}/gi,
  },
  {
    kind: 'private-ip',
    re: /\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b/g,
  },
  { kind: 'internal-host', re: /\b[a-z0-9][a-z0-9-]*\.(?:internal|corp|local|intranet|lan)\b/gi },
];

const EMAIL_RE = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g;

/**
 * Scan text and return the redacted form plus the kinds that fired.
 *
 * @param {string} text
 * @param {{ selfEmail?: string }} [opts] selfEmail is the local git identity, the
 *   one address left intact because it is already public in every commit.
 * @returns {{ text: string, findings: Array<{kind: string, count: number}> }}
 */
export function redact(text, opts = {}) {
  if (typeof text !== 'string') {
    throw new TypeError('redact() requires a string; refusing to write unscanned content');
  }
  const counts = new Map();
  let out = text;

  for (const { kind, re } of PATTERNS) {
    out = out.replace(re, () => {
      counts.set(kind, (counts.get(kind) || 0) + 1);
      return `<redacted:${kind}>`;
    });
  }

  const self = (opts.selfEmail || '').trim().toLowerCase();
  out = out.replace(EMAIL_RE, (m) => {
    if (self && m.toLowerCase() === self) return m;
    counts.set('email', (counts.get('email') || 0) + 1);
    return '<redacted:email>';
  });

  return {
    text: out,
    findings: [...counts.entries()].map(([kind, count]) => ({ kind, count })),
  };
}

/**
 * Redact every string field of a node.
 * Returns the cleaned node and the union of findings across all fields.
 */
export function redactNode(node, opts = {}) {
  const findings = new Map();
  const clean = { ...node };
  for (const field of ['title', 'body']) {
    if (typeof clean[field] !== 'string') continue;
    const r = redact(clean[field], opts);
    clean[field] = r.text;
    for (const f of r.findings) findings.set(f.kind, (findings.get(f.kind) || 0) + f.count);
  }
  return {
    node: clean,
    findings: [...findings.entries()].map(([kind, count]) => ({ kind, count })),
  };
}
